# Generated by ./update.sh - do not update manually!
# Last updated: 2026-01-10
{ fetchurl }:
let
  any-darwin = {
    version = "";
    src = fetchurl {
      url = "";
      hash = "";
    };
  };
in
{
  aarch64-darwin = any-darwin;
  x86_64-darwin = any-darwin;
  aarch64-linux = {
    version = "3.2.23-44343";
    src = fetchurl {
      url = "https://dldir1v6.qq.com/qqfile/qq/QQNT/94704804/linuxqq_3.2.23-44343_arm64.deb";
      hash = "sha256-hw7TwOQX6bs6AhwdVlGLwvu6gtHD4YcThPZKt+IZI/c=";
    };
  };
  x86_64-linux = {
    version = "3.2.23-44343";
    src = fetchurl {
      url = "https://dldir1v6.qq.com/qqfile/qq/QQNT/94704804/linuxqq_3.2.23-44343_amd64.deb";
      hash = "sha256-pCUnGcG+uK3ODaCev8MQzlDHnqVI9czkKVBXZdC/uoQ=";
    };
  };
}
