# Generated by ./update.sh - do not update manually!
# Last updated: 2026-07-24
{ fetchurl }:
let
  any-darwin = {
    version = "";
    src = fetchurl {
      url = "";
      hash = "";
    };
  };
in
{
  aarch64-darwin = any-darwin;
  x86_64-darwin = any-darwin;
  aarch64-linux = {
    version = "3.2.31-260710";
    src = fetchurl {
      url = "https://qqdl.gtimg.cn/qqfile/QQNT/9.9.32/release/c390e792/QQ_3.2.31_260710_arm64_01.deb";
      hash = "sha256-rGBDcfXEhqz2y/g91mfmIu4fSH0Mi9QlYn3m1o/jSXQ=";
    };
  };
  x86_64-linux = {
    version = "3.2.31-260710";
    src = fetchurl {
      url = "https://qqdl.gtimg.cn/qqfile/QQNT/9.9.32/release/c390e792/QQ_3.2.31_260710_amd64_01.deb";
      hash = "sha256-AvZ3/rHOAe0pOjx3YeXdhb15k29X3KpM21MXiuMOPW0=";
    };
  };
}
