url=$1

hash=$(echo "$url" | grep -oP '/QQNT/\K[^/]+')
version=$(echo "$url" | grep -oP 'linuxqq_\K[^_]+')

amd64_url="https://dldir1v6.qq.com/qqfile/qq/QQNT/${hash}/linuxqq_${version}_amd64.deb"
arm64_url="https://dldir1v6.qq.com/qqfile/qq/QQNT/${hash}/linuxqq_${version}_arm64.deb"

amd64_hash=$(nix-prefetch-url $amd64_url)
arm64_hash=$(nix-prefetch-url $arm64_url)

# use friendlier hashes
amd64_hash=$(nix hash convert --to sri --hash-algo sha256 "$amd64_hash")
arm64_hash=$(nix hash convert --to sri --hash-algo sha256 "$arm64_hash")

cat >sources.nix <<EOF
# Generated by ./update.sh - do not update manually!
# Last updated: $(date +%F)
{
  version = "$version";
  amd64_url = "$amd64_url";
  arm64_url = "$arm64_url";
  arm64_hash = "$arm64_hash";
  amd64_hash = "$amd64_hash";
}
EOF
