#!/usr/bin/env bash
set -e

url=${1:?Usage: update.sh URL}
filename=${url##*/}

case "$filename" in
  QQ_*_amd64_01.deb)
    artifact_prefix=${filename%_amd64_01.deb}
    ;;
  QQ_*_arm64_01.deb)
    artifact_prefix=${filename%_arm64_01.deb}
    ;;
  *)
    echo "Unsupported QQ download URL: $url" >&2
    exit 1
    ;;
esac

version_with_build=${artifact_prefix#QQ_}
linux_version=${version_with_build/_/-}
base_url=${url%/*}

linux_x86_64_url="${base_url}/${artifact_prefix}_amd64_01.deb"
linux_aarch64_url="${base_url}/${artifact_prefix}_arm64_01.deb"

linux_x86_64_hash=$(nix-prefetch-url "$linux_x86_64_url")
linux_aarch64_hash=$(nix-prefetch-url "$linux_aarch64_url")

# use friendlier hashes
linux_x86_64_hash=$(nix --extra-experimental-features nix-command hash convert --to sri --hash-algo sha256 "$linux_x86_64_hash")
linux_aarch64_hash=$(nix --extra-experimental-features nix-command hash convert --to sri --hash-algo sha256 "$linux_aarch64_hash")

cat >sources.nix <<EOF
# Generated by ./update.sh - do not update manually!
# Last updated: $(date +%F)
{ fetchurl }:
let
  any-darwin = {
    version = "$darwin_version";
    src = fetchurl {
      url = "$darwin_url";
      hash = "$darwin_hash";
    };
  };
in
{
  aarch64-darwin = any-darwin;
  x86_64-darwin = any-darwin;
  aarch64-linux = {
    version = "$linux_version";
    src = fetchurl {
      url = "$linux_aarch64_url";
      hash = "$linux_aarch64_hash";
    };
  };
  x86_64-linux = {
    version = "$linux_version";
    src = fetchurl {
      url = "$linux_x86_64_url";
      hash = "$linux_x86_64_hash";
    };
  };
}
EOF
